### PR TITLE
Comfirm account

### PR DESCRIPTION
**Pull request by Rittamx031**
## Related Tickets
[- ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/72875)

## WHAT (optional)
- Change number items `completed/total` in admin page.

## HOW
- I edit js file, inject not_vary_normal items in calculate function.

## WHY (optional)
- Because in previous version - number just depends on `normal` items. But in new version, we have `state` and `confirm_state` depends on both `normal` + `not_normal` items.

## Evidence (Screenshot or Video)
image
image
image
image
image

### CODE REVIEW

**Comment by Rittamx031** [comment]
ready

**Comment by vanvtt-0952** [comment]
commented

**Comment by Rittamx031** [comment]
> commented

em không thấy comment ạ

**Comment by Rittamx031** [comment]
ready

**Review by huongnt-2545 — APPROVED** [review]
merged

**Pull request merged**
